### ISSUE TITLE
Is it necessary for WhatsApp to be Business?

### ISSUE THREAD

**Issue by mnuaimi** [donaldjansen/BaileysCSharp#2]
When I try to send messages it does not send unfortunately

**Comment by donaldjansen** [comment]
Hi, I have not run any tests on WA Business, only normal WhatsApp.
Are you able to receive any messages?

**Comment by viniciusverasdossantos** [comment]
I managed to make it work by changing these two lines. I compared it with the typescript code.
1)
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/c29bd290-b216-4212-b1d3-9a4f183899f5)

2)
theirEphemeralPubKey?.ToByteString()

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/098922b1-d01a-4954-8806-b9e6b4b73934)
